desc "Give the cached slug for a given article title"
task :slug => :environment do
  # Is Credit Basics section in personal finance already in Credit Card?
  list = ["Big Bank or Small? Which is Right for You?",
          "What Everybody should know about Debit Cards",
          "To ATM or Not To ATM:  That is the Question",
          "Are you really safe at the ATM ?",
          "Should I file for Bankruptcy ?",
          "Obtaining a Secured Card",
          "The Real Story of American Credit Card Debt",
          "So what is a Credit Card, anyway?",
          "Credit or Cash?  Which Serves you Best?",
          "Credit Cards : The Good, The Bad, and The Ugly",
          "What are the different kinds of Credit ?",
          "Starting the Credit Game",
          "How to Make Your Credit Card Company Work for You",
          "What's the Problem with using Credit Cards?",
          "Do your Credit Cards Help you or Hurt You?",
          "Credit card-less – A problem or a solution to a problem?",
          "What you Need to Know about Making your Credit Card Work for You",
          "Credit Card deals with Credit Unions",
          "How to create a strong credit profile in your credit report",
          "Understanding Credit Card Limits",
          "5 Things Credit Cards owners Should know about Terms and Conditions",
          "Explaining Credit Disclosure Rights",
          "Changes in Credit Card Billing you Need to Know About",
          "What you Absolutely must Know about Fine Print",
          "How Credit Card Companies Rip you Off without your Knowledge",
          "Top 6 False Claims of Credit Card Companies",
          "Some nasty tricks of Credit Card Companies",
          "Credit Cards Penalizing More or Less ?",
          "6 Credit Card Secrets that Banks will Never tell You",
          "3 Tricky Things Credit Cards do to Take your Money while Giving you Little in Return",
          "Free Credit Cards : Don't be Fooled !",
          "Navigating future Credit Card Trends",
          "Savvy Credit Card Techniques",
          "What can Make Corporate Cards bad for Business ?",
          "How not Using your Credit Card can Cost you Money",
          "Is Dave Ramsey right about Credit Cards ?  ",
          "Before you Acquire a New Credit Card",
          "Credit Cards; The Types, the Terms You Must know Before getting One",
          "Hard to get Exclusive Credit Cards",
          "Do Teens Need a Personal Credit Card ?",
          "Making Credit Cards Work for You: The Basics",
          "How Can I Properly Manage my Credit Cards?",
          "Making Debt Work: How to Use Credit Cards Wisely",
          "What to do about Errors on your Credit Card",
          "Is Minimum Payment a good idea? ",
          "What you Need to Know about Paying Late and Modern Technology",
          "Is it Bad to carry a Credit Card Balance ?",
          "7 Things you Must know Before you do Balance Transfer",
          "Wait! Don't do a Balance Transfer before You know the Following   ",
          "How to Avoid Maxing out Credit Cards ",
          "Going over the Credit Limit – beware !",
          "10 Reasons why should Cancel your Credit Cards",
          "How to Close your Credit Cards the Right Way",
          "Tips on how to destroy your old Credit Cards",
          "How to Avoid Credit Mistakes",
          "Common Credit Mistakes ",
          "11 Tips to finding a good Credit Card Interest Rates",
          "10 Tips for avoiding Credit Card Problems",
          "12 Tips on How to use Credit Cards wisely",
          "Winning the Battles: Making Credit Cards Work for You",
          "How to take Control of your Credit Cards",
          "How to avoid Store Credit Cards Trap",
          "Advanced Tactics for Credit Card Users",
          "A Brief Overview of the various Types of Credit Cards",
          "What's the Difference between this Credit Card and that One?",
          "The Secret of Choosing the Best Credit Card",
          "Do you Have the Right Credit Card?",
          "How to Shop around for a Credit Card",
          " The Best Business Credit Card for You",
          "Get Annual Fee Free Credit Cards",
          "Best Credit Card worth the annual fee",
          "Credit Cards: Is Going Business Class worth It ?",
           "Best Student Credit Cards",
           "Are you a Student ? Do you need a Credit Card?",
           "Best Credit Cards for managing Debts",
           "The Best Credit Cards",
           "Do you still Love Credit Cards?",
           "Choosing the Perfect Card",
           "Finding the Perfect Card For You",
           "Targeted Credit Cards - What to Know",
           "Secure your Travel, Get a Credit Card!",
           "Credit Card Travel Rewards:  Not all are Equal",
           "Have Credit Card, will Travel Overseas ?",
           "An Overview of Airline Credit Cards",
           "Lower your Credit Card debt and Increase your Reward Points",
           "7 worst Rewards Credit Cards",
           "Rewards Cards, the best option!",
           "Are Credit Card Reward points really worthy ?",
           "Are Cash back Credit Cards really Worth It?",
           "Earn Bonus Points by using your Credit Cards",
           "Benefits of owning a joint Credit Card",
           "What you Need to Know about Adding an Authorized User to Your Credit Card",
           "Credit Cards can Help you Knock Down High Gas Prices",
           "Credit Cards: 3 Successful Strategies to Save Money",
           "Save Money via sensible use of Credit Cards ",
           "Credit Card Perks that you Never knew About",
           "How to use Credit Cards responsibly and Gain Benefits",
           "Avoiding Credit Related Traps and Scams",
           "Have you fallen for a Credit Card Scam?",
           "Credit Card Scams that are Perfectly Legal and How Not to Fall for Them",
           "How not to Get scammed and Get the Credit Card you Deserve",
           "How Best can Students use their Credit Cards?",
           "Send them to College with or without a Credit Card?",
           "Federal Credit Law History – From the Beginning",
           "Know the Credit Laws – They’re there to Protect You",
           "The Legal Side of the Credit Game",
           "Credit Cards in the post CARD Act Age",
           "Understanding the Fair Credit Reporting Act",
           "The Credit Agencies and the Laws that Protect You from Them",
           "Legislation and Lending",
           "Your Rights in the Credit Game",
           "Credit Scoring",
           "Things you Should know before Fixing Your Credit",
           "Can I do Credit Repair Myself ?",
           "Restoring Bad Credit – Risks of Doing it Yourself",
           "Can anyone Really Repair Your Credit? Is Credit Counseling Worthwhile?",
           "How to Repair your Credit ?",
           "8 Key Steps to Repair your Credit",
           "Forceful Tactics to Fix your Credit",
           "7 Ways to Build your Credit without using Credit Cards",
           "Pitfalls to avoid when Rebuilding Credit History",
           "How do I Rebuild my Credit History ?",
           "Rebuilding your Credit Score after Identity Theft",
           "How to Build or Rebuild your Credit",
           "How to shop for Best Credit Card Rates and Build your Credit",
           "Use your Credit to get Good Credit",
           "To Remove or Not to Remove Bad Credit. Is it Ethical ?",
           "Credit Resurrection : How to Begin Anew",
           "The Price of a Bad Reputation : Reestablishing Your Credit Score",
           "Better Credit by paying on Time",
           "Is Bad Credit a Life Sentence ?",
           "Improve your Credit by Stopping your Spending",
           "Credit Recovery",
           "Can companies Help Repair your Credit ?",
           "Warning Signs of a Credit Repair Scam",
           "New Credit Identity - A Scam you Should be Aware of",
           "Credit Dispute",
           "10 Guidelines to Help you Write an Effective Letter to Dispute Bad Credit",
           "Bad Credit: How a Credit Bureau will React to your Dispute and What Next Steps you Should Take",
           "Evaluating your Bad Credit Dispute results and taking Escalation Actions",
           "Erasing Credit Inquiries – You can Change the Past",
           "Other Creative Approaches to Repairing your Credit Rating",
           "Repair Options for Bad Credit History",
           "Fixing Correct Negative Entries in your Credit Report",
           "Your Credit History – What is it Exactly ?",
           "What you Don't know about Your Credit Report can Hurt You",
           "Credit Reports, Credit Scores, and your Fiscal Responsibility Report Card",
           "The Information on your Credit Report",
           "Breaking Down your Credit Report",
           "How to Get your Credit Report",
           "Purchasing regular Credit Reports, Comprehensive Reports, and your Credit Score",
           "The Life Span of the Average Credit Report",
           "How Long Things Stay on your Credit Report",
           "A Stable Credit Report",
           "The Rules of the Credit Reporting System Game",
           "The Rules for Credit Bureaus and Furnishers",
           "Imperfect Credit History and Getting Credit",
           "Laying out the Plan for your Credit Report",
           "Fixing Bad Information on your Credit Report",
           "The Not-So-Simple Correct Negative Entries in your Credit Report",
           "Creating a Good Credit Report",
           "Is Credit Report Monitoring Company Worth it?",
           "Who Can Look at Your Credit Report ?",
           "How do you set right your Credit History after Settling a Debt ?",
           "6 Truths you Must know to Manage your Credit Report",
           "Your Credit Report affects your Mortgage in a Big Way",
           "Credit and Your Employer",
           "Inside FICO",
           "Little Known facts about Credit Card Scores",
           "What everybody Should know about Credit Scores",
           "The Importance of Your Credit Score",
           "Credit Scores are Everywhere",
           "5 Things Not to do for your Credit Score",
           "Why is your Credit Score very important ?",
           "The Mystery of Credit Scores",
           "What is a Good Credit Score ?",
           "3 Aspects of Credit Score that you Should know",
           "Why you must Check Your Credit Score…Even if You have Perfect Credit",
           "Credit Scores and Insurance Premiums",
           "Who can Check your Credit Score and How that Affects You",
           "Do you Know who's Checking your Credit Score without Your Permission ?",
           "How Applying for Credit Affects your Credit Score",
           "Does checking your Own Credit hurt your Credit Score ?",
           "Does lowering Credit Card Limits improve your Credit Score ?",
           "Your Credit Score and your Insurance Rates",
           "How Lenders use your Credit Score",
           "Why Should you care about Your Credit Score ?",
           "Credit Score killers you Should know about",
           "What you Should know about Credit Score Models before Making a big Purchase",
           "Improve your Credit Score, 740 is the mark",
           "Do you Need to Fix your Credit Score Quickly?",
           "When Rapid Credit Rescoring will Benefit You",
           "How to Boost your Credit Score in just Two Months",
           "Pay down Debt to Raise Credit Scores",
           "Off Beat Things that will Lower your Credit Score",
           "Fighting the Good Fight  to Improve your Credit Score",
           "Pay Bills later and Improve your Business Credit",
           "How to Manage your Credit to Improve your Credit Scores",
           "How to Protect your Credit Score and Assets During a Divorce",
           "Actions that will Lower your Credit Score",
           "How to Manage your Joint Accounts and Improve your Credit Score",
           "How bad Spending Habits can Ruin your Credit",
           "All about Collection Agencies from the Inside  ",
           "12 Things you Should know about Debt Collectors",
           "What to do when you get Calls about a Debt you Don't Owe ?",
           "Debt Recovery",
           "What you Should know about Credit Card Collections",
           "Legal steps you can take if a Debt Collector violates your rights",
           "What a Debt Collector is or isn't Allowed to Do",
           "How to deal with a Collection Agency ?",
           "What is the Best Way to Negotiate with a Collection Agency?",
           "Debt and the Art of Negotiation",
           "Tips for Negotiating with Creditors, Lenders and Collection Agencies",
           "Dealing with Collection Agencies",
           "Talking to Creditors and Debt Collectors",
           "Negotiating with Creditors",
           "How do you negotiate with a Debt Collector ?",
           "Repossessions, Foreclosures and Government Creditors",
           "How does Repossession work ?",
           "How to Regain Possession of your Vehicle after Repossession ?",
           "How to Prevent Repossession of your Vehicle",
           "How can an Attorney help you when your Vehicle gets Repossessed ?",
           "Why working with a Debt Settlement firm is not a good idea",
           "Why you Need to get Settlement Agreements in Writing",
           "This is You Stopping the Bill Collectors",
           "When a Creditor takes you to Court",
           "Debt management - Where do I start?",
           "Basics of debt management",
           "Is Debt a bad thing ?",
           "Being Honest about Debt Problems",
           "Seeing both Sides of the Coin: The Advantages and Disadvantages of Debt",
           "The Big Debts: What you Should know",
           "Are all Debts bad ?",
           "Why is debt a good thing",
           "Risks of Long term Debt",
           "Credit Card Debt Problems",
           "Using Joint Credit to your Advantage",
           "Facing Debt Head On: Crafting a Financial Plan",
           "How to Reduce your Credit Card Debt",
           "How to Manage Credit Card Debt",
           "Dangerous loans",
           "6 Steps to Zero-Out Credit Card Debt  ",
           "Climbing out of a Quagmire of Debt ",
           "Getting out of Debt",
           "Mind over Money - Thinking Yourself to Debt Free",
           "8 Ways to Cut Costs and Pay off Credit Card Debt",
           "What options do I have for Paying off my Debt ?",
           "Ways to Raise Money to Pay off your Debts",
           "How does a Debt Management plan work?",
           "Tools to eliminate Credit Card Debt",
           "Are there any long term consequences to not paying your Debts ?",
           "Order of Repayment - The Sneakiest Credit Card trick Ever?",
           "Should you Pay Off old Debts ?",
           "Consolidating Debt - What are Your Options?",
           "What you Need to Know about Debt Consolidation",
           "How do I choose a good Credit Counseling agency ?",
           "Is a Credit Counselor Right for You ?",
           "What you Need to Know about Hiring a Credit Counselor",
           "What to Expect at a Credit Counselor",
           "How to select a good Credit Counselor",
           "5 Answers you Must know Before Hiring a Credit Counseling Service",
           "The Inside Scoop on Settling Debt",
           "How to pay Less than you Owe and Settle your Credit Card Debts",
           "Some Options to Pay Down Credit Debt for those with Bad Credit",
           "Some options to Pay Down Credit Debt for those with Good Credit",
           "Beyond Credit Card Debt – Stop spending and start Saving",
           "How to find Money for Debt Payoffs",
           "11 Tips to Raising Cash for Debt Payments",
           "Getting the Help you Need with Debt",
           "Ways to get extra Cash to Pay Off Credit Card Debt",
           "How to Negotiate with Credit Card Companies",
           "What to do When you have to Negotiate with Credit Card Companies",
           "The Risks involved in Negotiating your Credit Cards",
           "Carrying Unpaid Debt: How Can you Settle for Less than the Full Amount?",
           "Why you Should Never use a Debt Negotiation Firm",
           "The Truth about Debt Repayment Plans that you Absolutely Must know Before you Get One…",
           "What are my Options when I can't Pay my Taxes on time ?",
           "How to Settle with IRS for less than what you Owe ?",
           "Why you should always Pay your Taxes on Time",
           "What are my Options to avoid an Eviction from a Rented place ?",
           "How can I deal with Eviction ?",
           "Facing an Eviction",
           "What to do if the Court decides to Evict you ?",
           "How to keep your Home Away from the Auctioneer’s Block",
           "Judicial vs Non-judicial Foreclosure",
           "8 steps in a Mortgage Foreclosure",
           "How to prevent a Foreclosure",
           "What you can Do when you Can no Longer Afford your House",
           "How to Negotiate for your Home when in Financial Trouble ",
           "What to do When you Can’t Afford your Home",
           "Your Home and your Credit ",
           "How do Home Equity Loans work ?",
           "What are the different ways of getting a Home Equity Loan ?",
           "Why Not to Use your Home’s Equity",
           "How to negotiate with your Mortgage lender ?",
           "What are the things that I need to be wary of Mortgage Loans ?",
           "Considerations when Purchasing a Home",
           "Avoiding an Uncomfortable Fit: How to Find the Right Mortgage",
           "Your Guide to a Low Interest Rate on your Home Loan",
           "Must know Facts about Credit and Credit Scores when Buying a Home",
           "Your Blueprint for Getting your House Loan",
           "Is Refinancing your Home a good option ?",
           "How much Home can you Afford ?",
           "A Plan for Working toward your First Home",
           "Knowing how Much your Home is Worth: the Pitfalls of Home Equity Loans",
           "Home Loan Programs that can Make all the Difference in your Interest Rates",
           "The Real Difference between Pre-approval and Pre-qualified and Why you Should Care…",
           "Should you Refinance ?",
           "The Surprising Truth about What Really Makes up Our Identity  ",
           "Is ID Theft a Real Problem?",
           "Identity Theft can Happen to You",
           "Identity Theft wreaks Havoc",
           "Banking and identity theft - To be online or not?",
           "Don’t let an Identify Theft cheat you out of your dreams",
           "Staying Safe against Online Crime",
           "Criminal Repercussions of Identity Theft",
           "Are you Going to be the Next Victim of Identity Theft?  ",
           "Are you a victim of Computer Bank Scams?",
           "Secrets that Identity Thieves won't Tell You",
           "Identity Theft: Number one Scam",
           "9 Steps to Reclaim Your Finances after Identity Theft",
           "It’s Not my Debt! I Promise!",
           "Do ID tools cause problems?",
           "How do thieves commit identity theft?",
           "Shocking Truths about Identity Theft",
           "Are you Protected against ID Theft ?",
           "How to prevent ID Theft",
           "How to Avoid Identity Theft",
           "Little known Tricks of Identity Thieves and What you Can Do to Protect Yourself",
           "Your Privacy and Identity Protection",
           "How to Protect your Credit Card from Identity Theft",
           "How to Protect yourself on the Telephone from Identity Thieves",
           "The Most Common ways thieves get your Credit Cards without you Knowing",
           "What you Need to know about Moving day and Identity Theft ",
           "What you're Throwing out Could Cost you Your Identity",
           "The Secrets of what Identity Thieves do with Your Information  ",
           "Protect your Identity – You Can’t be too Careful",
           "Prevent Identity Theft : Phishing and fishing for your personal data",
           "10 Tips to Protect your SSN and Avoid Identity Theft",
           "Worried about Electronic Pickpocketing?  Foil Them!",
           "First Steps for Identity Theft Victims",
           "What you Must do if Your Identity is Stolen",
           "Rebuilding your Credit Score after Identity Theft",
           "Identity Theft Issues and Taxes",
           "Identity Theft and Bank Accounts",
           "Immediate Actions to Combat Criminal Identity Theft",
           "Prisoners and Identity Theft",
           "Give yourself a financial Check-Up",
           "Facing Finances: How to Calculate the Reality",
           "How do I check my Financial health ?",
           "12 Questions to Gauge your Financial Condition",
           "What you Should know about Transparency of Potential Lenders and Employers",
           "81 Ways to Reduce Spending",
           "How Do I Cut my Spending?",
           "Putting your Budget to Work",
           "How do I prioritize my expenses ?",
           "What are some of the reasons why people overspend ?",
           "Things Not to Do when in Financial Trouble",
           "Options for the Financially Overwhelmed",
           "Facing Challenges of Personal Financial Crisis",
           "How to get Back your Life and Credit",
           "Coping with Credit Crisis",
           "How to Get Out of a Credit Crisis",
           "4 Uncommon Credit Pitfalls",
           "How to Evaluate your Credit Emergency",
           "Pay off Plans for Getting out of a Credit Emergency",
           "Are you in a Financial Emergency ?",
           "Why you Need to Learn to Control your Credit",
           "How to handle Rent and Mortgage during Financial Difficulties",
           "What to do when you can’t Pay your Utilities",
           "Should you File for Bankruptcy to avoid Termination of Utilities ?",
           "How do you appeal to the Public Utilities Commission ?",
           "What can you do if you miss a couple of Utility Payments",
           "What to do if your Utilities are going to be Terminated ?",
           "How to Prevent Hospital Fraud and Reduce your Medical Expenses",
           "How to Manage your Medical Bills",
           "7 Tips to Lower your Medical Bills",
           "Home, Cars and Credit ",
           "Professional help to managing your money",
           "Create a Budget that Works",
           "Your Finances and Overspending",
           "The Three types of Budget",
           "12 Tips for Trimming down Fixed Expenses",
           "12 Tips for Trimming down Variable Expenses",
           "How do I plan my Financial future ?",
           "How to save your Financial Life",
           "What you Don't Know about Promissory Notes can Hurt your Friendship",
           "Don't make a Personal Loan to a Family Member Before you Read this...",
           "Tips to Cut your Phone Bills",
           "12 Tips for Saving on Hospital Bills and Funerals",
           "Manage your Finances to Save Money",
           "Earning more to make up your shortfall",
           "Debt and Divorce",
           "What you Need to Know about Assigned Debt in a Divorce",
           "How to Get your Finances in Order before the Divorce",
           "15 Action Steps you Must take to avoid Financial crunch after Divorce ",
           "Before you Even Think about Divorce, get Your Personal Credit in Good Shape",
           "Can you get a Reduction in your Child Support Payments ?",
           "What are the Different ways in which you can Manage your Child Support Payments ?",
           "Credit for your Kids",
           "14 Tips on How to Teach Money Management to Kids",
           "Help with Funding your or your Kid’s College Education",
           "What you Need to Know about Teaching kids Financial Responsibility",
           "Send them to College with or without a Credit Card?",
           "3 Options for Credit Cards for Children",
           "Credit and Kids",
           "What is the Appeals Process if the IRS wants to seize one of our Assets ?",
           "What can the IRS do to Recover its Money ?",
           "Is there Anything I can do apart from Filing an Appeal with the IRS  ?",
           "Is there any way to get my Assets back from the IRS ?",
           "How does the IRS Levy Work ?",
           "What are my Options when I can’t Pay Taxes on time?",
           "Why you should always Pay Your Taxes on Time",
           "Managing your Insurance Costs",
           "Ways to Pay Less for your Auto Insurance",
           "Calculating Your Insurance Score",
           "Things to Know about Shopping for Life Insurance",
           "How to Protect your Assets even if You're Dead",
           "How do I deal with Paying off Car Loan ?",
           "Buying a Car and your Credit",
           "Marriage and Your Credit",
           "Marriage and Finance – Things you should Know",
           "Credit, Debt, and Cutting Expenses",
           "Reducing Insurance Costs",
           "6 Things you Need to Consider before you Refinance",
           "What are the different kinds of Credit?",
           "Dangerous Loans",
           "Credit Mistakes that will Cost You",
           "Avoiding the Biggest Credit Mistakes",
           "Unsecured Credit",
           "What you Don't Know about Credit Interest Rate can Hurt You !",
           "What you should know before Going to Court for Credit Disputes",
           "Tips for Saving on College and Divorce",
           "What is the Collision Damage Waiver?",
           "How to save money on Car Rentals?",
           "5 Steps to Getting back on track to a Comfortable Retirement ",
           "How to Protect your IRAs and 401(k)s",
           "Options other than Retirement for Boomers",
           "Important Questions for Boomers to Answer Before Retirement",
           "Student Loans : The Ultimate Price of an Education",
           "Student Loans – a Trap for the Unwary",
           "Different kinds of Student Loans and their Repayment Options",
           "Student Loan Options for Financial Hardships",
           "Student Loan default and its Consequences",
           "What constitutes a Default on a Student Loan and Consequences of Default",
           "How can I get my Student Loans Canceled ?",
           "How does Student Loan Consolidation work ?",
           "Does Bankruptcy help me when I default on my Student Loans ?",
    
    
    ]
    4.times{ puts "." }
    list.each do |title|
      article = Article.find_by_title(title)
      if article
        puts "<p class=\"p3\"><a href=\"http://www.creditcardslogic.com/articles/#{article.cached_slug}\" target=\"_self\"> #{article.title} </a></p>"
      else
        puts "Failed to generate link for #{title}"
      end
    end
    4.times{ puts "." }


  # system "open 'http://localhost:3000/articles/best-credit-card-worth-the-annual-fee'"
end

desc "Generate hyperlinks for outline articles"
task :generate_links => :environment do
  categories = Category.all
  categories.each do |category|
    outliner = category.articles.where(:outline => true).first
    
    puts "<p class=\"p3\"><a href=\"http://www.creditcardslogic.com/articles/#{outliner.cached_slug}\" target=\"_self\"> #{outliner.title} </a></p>"
  end
  
end

desc "Generate hyperlinks for all articles"
task :generate_hyperlinks => :environment do
  articles = Article.all

  # <table>
  # <tr>
  # <td> Article Title</td>
  # <td>Link</td>
  # </tr>
  
  articles.each do |article|
    puts "<tr><td>#{article.title}</td>  <td>http://www.creditcardslogic.com/articles/#{CGI.escape(article.cached_slug)}</td></tr>"      
  end
  # </table>
end